parameters:
  data_path: /ECG_forecasting/Dataset
  divisore_threshold: 4
  soglia: 128
  raggio: 1
  soglia_distanza: 10
  interpolate: False
  num_points: null
  coordinates_pdf: [10, 690, 2540, 1900]