common:
  fp16: false
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  # wandb_project: question-answering

checkpoint:
  save_dir: checkpoints
  best_checkpoint_metric: em_accuracy
  maximize_best_checkpoint_metric: true
  save_interval: 1
  keep_last_epochs: 1
  save_interval_updates: 0
  no_epoch_checkpoints: false

task:
  _name: ecg_question_answering
  data: ???
  normalize: false
  enable_padding: true

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 256
  valid_subset: "valid,test"
  validate_interval: 1

distributed_training:
  distributed_world_size: 1

criterion:
  _name: binary_cross_entropy_with_logits
  report_auc: true
  per_log_keys: [question_type1, question_type2, question_type3, attribute_id]

optimization:
  max_update: 50000
  lr: [0.0001]
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: blind_transformer_qa
  num_labels: ???

  dropout: 0.0
  attention_dropout: 0.0
  activation_dropout: 0.1
  # encoder_layerdrop: 0.1

  encoder_layers: 12
  encoder_embed_dim: 768

  apply_mask: false
