common:
  fp16: false
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  # wandb_project: grounding-classification

checkpoint:
  save_dir: checkpoints
  best_checkpoint_metric: accuracy
  maximize_best_checkpoint_metric: true
  save_interval: 1
  keep_last_epochs: 1
  save_interval_updates: 0
  no_epoch_checkpoints: false
  # patience: 20

task:
  _name: ecg_classification
  data: ???
  path_dataset: true
  load_specific_lead: true
  enable_padding: true
  enable_padding_leads: true
  filter: false
  normalize: false
  mean_path: null
  std_path: null

dataset:
  num_workers: 6
  max_tokens: null 
  batch_size: 128
  train_subset: "train"
  valid_subset: "valid,test"
  validate_interval: 2

distributed_training:
  distributed_world_size: 1

criterion:
  _name: multi_head_binary_cross_entropy
  report_auc: true
  log_per_class: false
  per_log_keys: [attribute_id]

optimization:
  max_update: 100000
  lr: [0.0001]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08
  weight_decay: 0.0001

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: nejedly2021resnet_classifier
  num_labels: ???
  model_path: null
  no_pretrained_weights: true

  indicate_leads: true
  use_mha: true

  final_dropout: 0.5
  in_d: 12