common:
  fp16: false
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  # wandb_entity: ecg-pretraining
  # wandb_project: question-answering

checkpoint:
  save_dir: checkpoints
  best_checkpoint_metric: partial_accuracy
  maximize_best_checkpoint_metric: true
  save_interval: 1
  keep_last_epochs: 1
  save_interval_updates: 0
  no_epoch_checkpoints: false
  # patience: 30

task:
  _name: ecg_question_answering
  data: ???
  normalize: false
  enable_padding: true

dataset:
  num_workers: 6
  max_tokens: null 
  batch_size: 64
  valid_subset: "valid,test"
  validate_interval: 1

distributed_training:
  distributed_world_size: 1

criterion:
  _name: binary_cross_entropy_with_logits
  report_auc: true
  multi_class_multi_label: true
  per_log_keys: [question_type, template_id, attribute_id]

optimization:
  max_epoch: 50
  lr: [0.00005]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08
  weight_decay: 1e-4

lr_scheduler:
  _name: fixed

model:
  _name: resnet_lstm_classifier
  num_labels: 108
  model_path: null
  no_pretrained_weights: true

  configuration: resnet50
  in_d: 12

  lstm_input_dim: 768
  lstm_embed_dim: 512
  lstm_num_layer: 2
  
  apply_norm: false