common:
  all_gather_list_size: 4096000
  log_format: tqdm
  log_interval: 10
  wandb_entity: ecg-pretraining
  wandb_project: question-answering

common_eval:
  path: ???
  quiet: false
  model_overrides: "{'model_path': None, 'no_pretrained_weights': True}"

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 128
  valid_subset: "test"
  fixed_validation_seed: 1

task:
  _name: ecg_question_answering
  model_name: null
  data: ???
  normalize: false
  enable_padding: true

model: null